name 'jenkins'
maintainer 'Ken Erwin'
maintainer_email 'ken@devopslibrary.com'
license 'all_rights'
description 'Installs/Configures jenkins'
long_description 'Installs/Configures jenkins'
source_url 'https://github.com/devopslibrary/jenkins'
issues_url 'https://github..com/devopslibrary/jenkins'
version '1.0.0'
chef_version '>= 13'
supports 'linux'
