Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "ubuntu/xenial64"
  c.vm.hostname = "jenkins-ubuntu-xenial64.vagrantup.com"
  c.vm.network(:forwarded_port, {:guest=>80, :host=>8080})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.gui = false
  end
end
